<?php

namespace BlogBundle\Entity;

/**
 * FileLoaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileLoaderRepository extends \Doctrine\ORM\EntityRepository
{
}
