security:
    encoders:
        BlogBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                 providers: [in_memory, db_user]
        db_user:
                entity:
                    { class: BlogBundle:User, property: username }
        in_memory:
                    memory:
                        users:
                            alex: { password: 12345qwerty, roles: 'ROLE_ADMIN', }

    firewalls:

            secured_area:
                pattern:    ^/
                anonymous: true
                http_basic: ~
                form_login:
                                            login_path: /login

                                            default_target_path: /welcome
                                            always_use_default_target_path: true
                logout:
                                        path:   /logout
                                        target: /login


    access_denied_url: /access_denied

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/welcome, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/read_post, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/userget, roles: ROLE_ADMIN }
        - { path: ^/commdel, roles: ROLE_ADMIN }
